server:
  port: 9090
  ssl:
    enabled: true
    key-alias: gateway-keystore
    key-store-password: leoHenry
    key-store: src/main/resources/certs/gateway-keystore.p12
    key-store-type: PKCS12

app:
  key:
    encryption:
      backend: stillkeepitsimpleAtTheBackEnd
      frontend: justkeepitsimpleAlsoAtTheFrontEnd
---
spring:
  cloud:
    gateway:
      default-filters:
        #        - RemoveRequestHeader=ClientId
        - name: GatewayGlobalFilter
      routes:

        - id: swagger
          uri: http://localhost:60098/
          predicates:
            - Path=/**
            #            - name: TokenPostFilter

        - id: token
          uri: http://localhost:60098/
#          uri: http://35.194.18.85:9090/
          predicates:
            - Path=/api/v1/token/**
          filters:
            - name: EncryptDecryptFilter


        - id: wallet
          uri: http://localhost:60098/
          predicates:
            - Path=/api/v1/wallet/**
          filters:
            - name: TokenPreFilter

        - id: account
          uri: http://localhost:60098/
          predicates:
            - Path=/api/v1/account/**
          filters:
            - name: TokenPreFilter

        - id: bank
          uri: http://localhost:60098/
          predicates:
            - Path=/api/v1/bank/**
          filters:
            - name: TokenPreFilter

        - id: client
          uri: http://localhost:60098/
          predicates:
            - Path=/api/v1/client/**
          filters:
            - name: TokenPreFilter

        - id: transactions
          uri: http://localhost:60098/
          predicates:
            - Path=/api/v1/transactions/**
          filters:
            - name: TokenPreFilter

        - id: payment
          uri: http://localhost:60098/
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - name: TokenPreFilter

        - id: role
          uri: http://localhost:60098/
          predicates:
            - Path=/api/v1/role/**
          filters:
            - name: TokenPreFilter
#    httpclient:
#      ssl:
#        useInsecureTrustManager: true