server:
  port: 80
  #  ssl:
  #    enabled: true
  #    key-alias: ${ALIAS}
  #    key-store-password: ${KEYSTORE_PASS}
  #    key-store: ${KEY_STORE}
  #    key-store-type: ${KEY_STORE_TYPE}
  #    key-store-type: PKCS12
  #    key-alias: gateway
  #    key-store: src/main/resources/ebininfosoft-ssl-key.p12

app:
  key:
    encryption:
      backend: ${KEY_BACK}
      frontend: ${KEY_FRONT}
  inventory-base-url: http://inventory-svc:80/
  user-base-url: http://user-svc:80/
  order-base-url: http://order-svc:80/
  nofication-base-url: http://notification-svc:80/
  wallet-base-url: http://wallet-svc:80/
  auth-serve: http://auth-svc:80/auth-serve

  inventory-base-path: /api/v1/inventory
  user-base-path: /api/v1
  order-base-path: /api/v1
  nofication-base-path: /api/v1
  wallet-base-path: /api/v1
  auth-serve-path: /api/v1



---
spring:
  cloud:
    gateway:
      default-filters:
          #        - RemoveRequestHeader=ClientId
      - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
#          - name: GatewayGlobalFilter

#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowed-origins: "*"
#            allowed-methods: "*"
#            allowed-headers: "*"
#            allow-credentials: true
          #            allowedOrigins:
          #              - min.com.ng
          #              - inventory.min.com.ng
          #              - user.min.com.ng
          #              - admin.min.com.ng
          #            allowedMethods:
          #              - GET
          #              - POST
          #              - PUT
          #              - PATCH
      routes:

        #Auth Serve

        - id: auth-swagger
          uri: ${app.auth-serve}
          predicates:
            - Path=/auth-serve/**

        - id: token
          uri: ${app.auth-serve}
          predicates:
            - Path=${app.auth-serve-path}/token/**
          filters:
            - name: EncryptDecryptFilter

        - id: role
          uri: ${app.auth-serve}
          predicates:
            - Path=${app.auth-serve-path}/role/**

        - id: permission
          uri: ${app.auth-serve}
          predicates:
            - Path=${app.auth-serve-path}/permission/**

        - id: policy
          uri: ${app.auth-serve}
          predicates:
            - Path=${app.auth-serve-path}/policy/**

        # Wallet System

        - id: wallet-swagger
          uri: ${app.wallet-base-url}
          predicates:
            - Path=/wallet-system/**

        - id: wallet
          uri: ${app.wallet-base-url}
          predicates:
            - Path=${app.wallet-base-path}/wallet/**
        - id: account
          uri: ${app.wallet-base-url}
          predicates:
            - Path=${app.wallet-base-path}/account/**
        - id: bank
          uri: ${app.wallet-base-url}
          predicates:
            - Path=${app.wallet-base-path}/bank/**
        - id: transactions
          uri: ${app.wallet-base-url}
          predicates:
            - Path=${app.wallet-base-path}/transactions/**
        - id: payment
          uri: ${app.wallet-base-url}
          predicates:
            - Path=${app.wallet-base-path}/payment/**

        #Notification services

        - id: notification
          uri: ${app.nofication-base-url}
          predicates:
            - Path=${app.nofication-base-path}/email

        #Order services

        - id: order-swagger
          uri: ${app.order-base-url}
          predicates:
            - Path=${app.order-base-path}/swagger-doc-minng/**

        - id: order-quotation
          uri: ${app.order-base-url}
          predicates:
            - Path=${app.order-base-path}/quotation/**

        - id: order-rfq
          uri: ${app.order-base-url}
          predicates:
            - Path=${app.order-base-path}/rfq/**

        - id: order-inquiry
          uri: ${app.order-base-url}
          predicates:
            - Path=${app.order-base-path}/inquiry/**

        - id: order-invoice
          uri: ${app.order-base-url}
          predicates:
            - Path=${app.order-base-path}/invoice/**

        - id: order-order
          uri: ${app.order-base-url}
          predicates:
            - Path=${app.order-base-path}/order/**

        #Inventory Service

        - id: inventory-swagger
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/documentation/**

        - id: inventory-category
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/category/**

        - id: inventory-product
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/product/**

        - id: inventory-order-types
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/order-types/**

        - id: inventory-vat
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/vat/**


        - id: inventory-logistics
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/logistics/**


        - id: inventory-dimension-units
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/dimension-units/**


        - id: inventory-weight-units
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/weight-units/**


        - id: inventory-bulk-units
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/bulk-units/**


        - id: inventory-shipping-class
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/shipping-class/**


        - id: inventory-branch
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/branch/**


        - id: inventory-store
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/store/**

        - id: inventory-business-type
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/business_type/**

        - id: inventory-production-capacity
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/production-capacity/**

        - id: inventory-trade-association
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/trade_association/**

        - id: inventory-production-certificate
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/production_certificate/**

        - id: inventory-multimedia
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/multimedia/**

        - id: inventory-form
          uri: ${app.inventory-base-url}
          predicates:
            - Path=${app.inventory-base-path}/form/**

        # User service

        - id: user-swagger
          uri: ${app.user-base-url}
          predicates:
            - Path=api/v1/user/documentation

        - id: user-auth
          uri: ${app.user-base-url}
          predicates:
            - Path=${app.user-base-path}/auth/**

        - id: user-user
          uri: ${app.user-base-url}
          predicates:
            - Path=${app.user-base-path}/user/**

        - id: user-roles
          uri: ${app.user-base-url}
          predicates:
            - Path=${app.user-base-path}/roles/**

        - id: user-privileges
          uri: ${app.user-base-url}
          predicates:
            - Path=${app.user-base-path}/privileges/**

        - id: user-countries
          uri: ${app.user-base-url}
          predicates:
            - Path=${app.user-base-path}/countries/**

        - id: user-states
          uri: ${app.user-base-url}
          predicates:
            - Path=${app.user-base-path}/states/**

        - id: user-cities
          uri: ${app.user-base-url}
          predicates:
            - Path=${app.user-base-path}/cities/**